Pause Game error 해결
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-02 pull request #122
Opened 2024-12-04 12:05 UTC by dgg1dbg

Pause Game error 해결

## Related Issue(s)

resolves #121

## PR Description

- pause 버튼을 누른 후, space 또는 enter 버튼등을 누르면 pause가 활성화되어있어 pause 버튼이 눌림
- pause 버튼을 누른 후, focus가 해지되는 스크립트 추가

### Changes Included

- [ ] Added new feature(s)
- [ ] Fixed identified bug(s)
- [ ] Updated relevant documentation

### Screenshots (if UI changes were made)

Attach screenshots or GIFs of any visual changes. (Only for frontend-related changes)

### Notes for Reviewer

Any specific instructions or points to be considered by the reviewer.

---

## Reviewer Checklist

- [ ] Code is written in clean, maintainable, and idiomatic form.
- [ ] Manual testing has been performed to ensure the PR works as expected.
- [ ] Code review comments have been addressed or clarified.

---

## Additional Comments

Add any other comments or information that might be useful for the review process.

2024-12-07 08:34 UTC, gyusang requested changes

2024-12-07 08:34 UTC, gyusang commented on Assets/Scenes/LevelOneScene.unity
> -  musicClip: {fileID: 8300000, guid: 5ebbe520d33e94e24a2cb4c3303a17a8, type: 3}
musicClip이 삭제된 것 같은데 다시 넣어주어야 할 것 같습니다!

2024-12-07 09:06 UTC, snjlee58 reviewed
버그는 잘 해결된거같습니다!! 수고하셨습니다!

2024-12-09 08:54 UTC, gyusang approved these changes
음악 문제 없이 재생되는 것 확인했습니다

2024-12-09 16:47 UTC, merged