ft/level-select
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-02 pull request #13
Opened 2024-10-30 11:48 UTC by dgg1dbg

2024-10-30 11:55 UTC, gyusang requested changes

2024-10-30 11:55 UTC, gyusang commented on Assets/LevelSelectScene.unity
This should be moved under Scenes/

2024-11-02 11:41 UTC, gyusang commented
@snjlee58 리뷰 부탁드립니다 :)

2024-11-02 12:03 UTC, snjlee58 approved these changes

2024-11-03 11:58 UTC, merged