[#3] Added Player Movement Logic, and Simple Animations
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-02 pull request #14
Opened 2024-11-02 15:39 UTC by vexatone

resolves #3 

Player의 움직임을 간단히 구현해봤습니다.
Player가 움직이고 있는 도중에 새로운 움직임 명령이 들어올 경우, 그 명령은 무시됩니다.
또한 움직이고자 하는 방향에 장애물이 있을 경우, 그 명령은 무시됩니다.

Unity Engine 내부에서 GameObject tile을 배치한 경우, 그 tile은 tile으로 판정을 하지 않는 듯합니다.
이로 인해 Tilemap을 사용한 특정 위치에서의 장애물 유무 판단이 어려워, 일단 Raycast로 구현했습니다.

2024-11-04 05:25 UTC, gyusang requested changes

2024-11-04 05:25 UTC, gyusang commented on Assets/Scripts/InputManager.cs
> +    [SerializeField] private KeyCode playerLeftKey = KeyCode.A;
SerializeField는 어떤 기능인가요?

2024-11-04 05:25 UTC, gyusang commented on Assets/Scripts/PlayerBehaviour.cs
> +        if (!_animator && _animator.IsInTransition(0)) return;  // Condition check: Is player moving
`!_animator`가 null check를 하는 것인가요?
`_animator`가 null인 경우에도 return하거나 error를 내는 게 어떨까요?

2024-11-04 05:25 UTC, gyusang commented on Assets/Scripts/PlayerBehaviour.cs
> +        };
이부분을 Direction enum의 method로 구현하면 더 깔끔할 거 같긴 한데,
일단 작동하니 백로그로 넣어두면 될듯합니다.

2024-11-04 05:25 UTC, gyusang commented on Assets/Scripts/PlayerBehaviour.cs
> +            _ => Vector3.zero
이 경우가 존재하나요? 에러를 던지는 게 좋을 듯 합니다.

2024-11-04 05:25 UTC, gyusang commented on Assets/Scripts/PlayerBehaviour.cs
> +        UpdatePos(direction);
이부분이 제가 플레이할 때 싱크가 살짝 안 맞아서 A -> B 갔다가 A 1프레임정도 돌아왔다가 다시 B로 순간이동하는 것처럼 보입니다.

https://github.com/user-attachments/assets/f3471e56-f2c4-4563-8ea9-e397e73bdbc4

비슷한 이유로 장애물도 통과하기도 하네요.
구현을 변경해야 할 것 같습니다.

2024-11-04 09:58 UTC, junis3 commented on Assets/Scripts/PlayerBehaviour.cs
> +                _animator.SetTrigger("JumpFront");
네 종류 애니메이션이 별개로 있는 것보다, (1) 해당하는 방향으로 회전 (2) "앞으로 점프" 애니메이션 재생 을 실행하는 걸로 하는게 어떨까요?

2024-11-04 09:58 UTC, junis3 commented on Assets/Scripts/PlayerBehaviour.cs
> +        if (!_animator && _animator.IsInTransition(0)) return;  // Condition check: Is player moving
앞선 리뷰 (수정 검토 요청) 와 별개로, 여기에 있는 && → || 로 바뀌어야 할 듯해요~

2024-11-04 09:58 UTC, junis3 commented on Assets/Scripts/PlayerBehaviour.cs
> +        UpdatePos(direction);
0.51초로 고정하지 말고 Update / FixedUpdate 함수에서 애니메이션이 끝났는지 Animator 컴포넌트로 직접 확인하면 해결되지 않을까 싶어요. GPT는 이런 코드를 추천하네요 ㅋㅋ

void Update() {
    AnimatorStateInfo stateInfo = animator.GetCurrentAnimatorStateInfo(0);
    if (stateInfo.IsName("YourAnimationName") && stateInfo.normalizedTime >= 1.0f) {
        YourFunction();
    }
}

2024-11-05 00:35 UTC, vexatone commented on Assets/Scripts/InputManager.cs
> +    [SerializeField] private KeyCode playerLeftKey = KeyCode.A;
Unity의 Serialization에 대해서는 https://docs.unity3d.com/ScriptReference/SerializeField.html를 참고하면 될 것 같습니다.

Unity에서는 각 component에서 사용되는 field 중 Unity식으로 serialize된 field만 inspector에 노출시키는데, Unity가 기본적으로 public field만 serialize하기 때문에 private field를 serialize하려면 SerializeField를 붙여줘야 합니다.

2024-11-05 00:58 UTC, vexatone commented on Assets/Scripts/PlayerBehaviour.cs
> +        if (!_animator && _animator.IsInTransition(0)) return;  // Condition check: Is player moving
일단 Animation 관련 코드는 전부 제거하였습니다.

2024-11-05 00:58 UTC, vexatone commented on Assets/Scripts/PlayerBehaviour.cs
> +        };
Unity의 enum은 기본적으로 method를 만드는 걸 허용하지 않기에, Direction의 구현을 enum 대신 struct로 바꾸었습니다. `direction.Value`를 통해 direction vector의 값을 가져올 수 있습니다.

2024-11-05 00:58 UTC, vexatone commented on Assets/Scripts/PlayerBehaviour.cs
> +            _ => Vector3.zero
넵. 수정했습니다.

2024-11-05 00:59 UTC, vexatone commented on Assets/Scripts/PlayerBehaviour.cs
> +        UpdatePos(direction);
일단은 Animator 관련 코드를 전부 제거했습니다.

2024-11-05 00:59 UTC, vexatone commented on Assets/Scripts/PlayerBehaviour.cs
> +                _animator.SetTrigger("JumpFront");
그 방법이 아무래도 좋을 것 같네요. 일단은 Animation 관련 코드를 전부 제거했지만, 추후 실제 캐릭터 모델의 Animation을 구현할 때 반영하겠습니다.

2024-11-05 00:59 UTC, vexatone commented
잠시만요.. 일단 이 Scripts 폴더 conflict부터 해결해볼게요

2024-11-06 10:22 UTC, junis3 approved these changes
플레이어 회전 등 로직이 모두 제거되고 딱 이동만 남았군요 ㅠㅠ 나머지는 차차 채워가기로 하고 일단 approve할게용

2024-11-09 04:07 UTC, gyusang approved these changes

2024-11-09 04:08 UTC, merged

2024-11-09 13:23 UTC, gyusang commented on Assets/Scripts/PlayerBehaviour.cs
> +        StartCoroutine(nameof(CooldownRoutine));
`StartCoroutine(CooldownRoutine())` 대신에 string으로 호출하는 방법도 있군요? 신기합니다.

2024-11-09 13:25 UTC, gyusang reviewed
cooldown이 몇초인지 시각적으로 표시가 안 돼서 어색하긴 한데 나중에 애니메이션 추가되면 괜찮을 것 같습니다.
사후리뷰 완료했습니다. LGTM!