[#9] 카메라 이동 구현
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-02 pull request #19
Opened 2024-11-09 11:17 UTC by junis3

- 카메라 이동을 구현했습니다. 일정 속도로 움직이다가 플레이어가 앞으로 나가면 따라갑니다.
- 일정 선 뒤로 이동하면 라이프가 깎입니다. 라이프 5개가 모두 깎이면 게임오버됩니다.
  - "일정 선 뒤로 이동 판정": CameraBehaviour, "라이프 깎임": PlayerBehaviour, "게임 오버": GameController로 나눠뒀습니다.
  - 디자인 패턴상 이상하거나 제안사항있으면 말해주세요

Resolves #9

2024-11-09 12:04 UTC, gyusang reviewed
고생하셨습니다!
잘 구현하셨네요.
코멘트 남겼으니 확인 부탁드립니다.

2024-11-09 12:04 UTC, gyusang commented on Assets/Scripts/PlayerBehaviour.cs
> +        }
dx = 1, -2, 3, -4, ...
x = 0, 1, -1, 2, -2, ...이 되는거군요
좋습니다!
맵 배치를 x좌표 0이 가운데가 되게만 하면 될 거 같아요

2024-11-09 12:05 UTC, vexatone requested changes
이상입니다. 기능상의 문제는 없어보이니, 코드 디자인적으로만 조금 신경써주시면 될 것 같습니다.

2024-11-09 12:05 UTC, vexatone commented on Assets/Scripts/GameManager.cs
올려주신 코드를 보면 각 object 생성 시 script에서 GameManager object의 이름을 이용해 GameManager를 불러오는 방식으로 구현이 되어있는 것 같은데, 여기다가 Singleton 패턴을 적용하는 편이 좋을 것 같습니다.

Unity에서 Singleton Pattern을 사용하는 방법에 대해서는 [여기](https://gamedevbeginner.com/singletons-in-unity-the-right-way/)를 참고하시면 좋을 것 같습니다.

2024-11-09 12:05 UTC, vexatone commented on Assets/Scripts/CameraBehaviour.cs
> +            currentPos += player.transform.position.z - (currentPos + 5.0f);
Unity에서 제공해주는 함수인 `Mathf.Clamp()`를 사용하는 편이 깔끔할 것 같습니다.

`Mathf.Clamp()`에 관해서는 [여기](https://docs.unity3d.com/ScriptReference/Mathf.Clamp.html)를 참고하세요.

2024-11-09 12:05 UTC, vexatone commented on Assets/Scripts/CameraBehaviour.cs
> +        );
Unity는 `Vector3` 간의 덧셈 연산을 지원하기 때문에, `Vector3` 끼리의 합으로 표현하는 게 좋아보입니다.

2024-11-09 12:05 UTC, vexatone commented on Assets/Scripts/CameraBehaviour.cs
> +        if (player.transform.position.z < currentPos - 2)
카메라 시점이 아직 확정은 아닌지라... -2를 하드코딩하는 것보다는 field로 정의해두고 참조하는 것이 좋을 듯합니다.

2024-11-09 12:05 UTC, vexatone commented on Assets/Scripts/PlayerBehaviour.cs
> +        transform.position += new Vector3(0, 0, 7);
마찬가지로, `new Vector3(0, 0, 7)` 부분을 하드코딩하기보다는 field로 정의해놓고 참조하는 편이 좋을 것 같습니다.

2024-11-09 12:05 UTC, vexatone commented on Assets/Scripts/PlayerBehaviour.cs
> +using Unity.VisualScripting;
아마 IDE를 사용하시면서 IDE가 잘못된 패키지에 대한 using 구문을 넣은 것 같은데, 현재 사용되지 않는 패키지에 대한 using 구문은 제거하는 게 보기에 깔끔할 것 같습니다.

2024-11-09 12:49 UTC, vexatone commented on Assets/Scripts/GameManager.cs
MonoBehaviour를 사용하지 않고 구현하는 방법은 [여기](https://glikmakesworld.tistory.com/2)를 참고하면 좋을 것 같습니다.

2024-11-11 11:29 UTC, gyusang approved these changes
좋습니다!

2024-11-11 14:03 UTC, junis3 commented on Assets/Scripts/PlayerBehaviour.cs
> +        }
말씀대로 멥 가운데 좌표에서 리스폰되는 게 좋을 거 같아서, 고정된 _respawnX에서 리스폰되도록 바꾸어두었어요~ 확인 부탁드려요!

2024-11-13 05:42 UTC, gyusang commented on Assets/Scripts/PlayerBehaviour.cs
> +        }
확인했습니다 좋네요!

2024-11-13 06:17 UTC, vexatone approved these changes
아래 달아놓은 문제점 이외에 별다른 문제점은 보이지 않네요. 수고하셨습니다!

2024-11-13 06:17 UTC, vexatone commented on Assets/Scripts/PlayerBehaviour.cs
> +        stageManager = GameObject.Find("stageManager");
GameManager object 이름이 바뀌지 않아, 이 부분에서 stageManager가 null이 되는 것 같습니다.
다만 Unity 특성상 씬을 잘못 건드렸다가 merge conflict가 나는 ~~더 귀찮은~~ 상황이 발생할 가능성이 높아, merge하고 추후 별도 작업을 통해 수정하는 것이 좋아보입니다.

2024-11-13 10:03 UTC, junis3 commented on Assets/Scripts/PlayerBehaviour.cs
> +        stageManager = GameObject.Find("stageManager");
dev에서 머지 → Incoming 받아들임 (브랜치 작업 discard) → StageManager 재추가 방법으로 다시 추가해두었습니다.

2024-11-13 10:15 UTC, junis3 commented on Assets/Scripts/GameManager.cs
구현 완료했습니다. 확인 부탁드립니다!

2024-11-13 10:22 UTC, vexatone approved these changes

2024-11-13 10:24 UTC, merged